language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t harriswong27/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harriswong27/docker-react npm run test -- --coverage
